insert into
    SimiladorDNC_Lappiz_GrupoUsuario (
        NombreGrupo,
        CEDescripcion,
        AplicaFiltro,
        CodigoGrupo
    )
values
    ('ARAMIREZCORF', 'AVANZADA', 'SI', '11'),
    ('ARAMIREZCORFCEOS', 'AVANZADA', 'SI', '12'),
    ('ATAMAYOCORFCEOS', 'AVANZADA', 'SI', '13'),
    ('AZCAMACHO', 'AVANZADA', 'SI', '14'),
    ('AZPACHECO', 'AVANZADA', 'SI', '15'),
    ('AZPACHECOCEOS', 'AVANZADA', 'SI', '16'),
    ('AZRODRIGUEZ', 'AVANZADA', 'SI', '17'),
    ('AZRODRIGUEZCEOS', 'AVANZADA', 'SI', '18'),
    ('AZSANDOVAL', 'AVANZADA', 'SI', '19'),
    ('AZTAFUR', 'AVANZADA', 'SI', '20'),
    ('AZVARGAS', 'AVANZADA', 'SI', '21'),
    ('CEOSJURIDICO', 'AVANZADA', 'SI', '22'),
    ('CZCARRERA', 'AVANZADA', 'SI', '23'),
    ('CZHUERTAS', 'AVANZADA', 'SI', '24'),
    ('CZHUERTASCEOS', 'AVANZADA', 'SI', '25'),
    ('CZMARTINEZ', 'AVANZADA', 'SI', '26'),
    ('CZMARTINEZCEOS', 'AVANZADA', 'SI', '27'),
    ('CZMOSCOSO', 'AVANZADA', 'SI', '28'),
    ('CZMOSCOSOCEOS', 'AVANZADA', 'SI', '29'),
    ('CZRAMIREZ', 'AVANZADA', 'SI', '30'),
    ('CZSALDARRIAGA', 'AVANZADA', 'SI', '31'),
    ('CZSALDARRIAGACEOS', 'AVANZADA', 'SI', '32'),
    ('CZSANTAMARIA', 'AVANZADA', 'SI', '33'),
    ('CZSANTAMARIACEOS', 'AVANZADA', 'SI', '34'),
    ('CZSANTIAGO', 'AVANZADA', 'SI', '35'),
    ('CZSANTIAGOCEOS', 'AVANZADA', 'SI', '36'),
    ('CZTRUJILLO', 'AVANZADA', 'SI', '37'),
    ('CZTRUJILLOCEOS', 'AVANZADA', 'SI', '38'),
    ('DZCANARETE', 'AVANZADA', 'SI', '39'),
    ('DZCASTANEDA', 'AVANZADA', 'SI', '40'),
    ('DZCASTANEDACEOS', 'AVANZADA', 'SI', '41'),
    ('DZDELAESPRIELLA', 'AVANZADA', 'SI', '42'),
    ('DZDELAESPRIELLACEOS', 'AVANZADA', 'SI', '43'),
    ('DZDIAZ', 'AVANZADA', 'SI', '44'),
    ('DZDIAZCEOS', 'AVANZADA', 'SI', '45'),
    ('DZLONDONO', 'AVANZADA', 'SI', '46'),
    ('DZLONDONOCEOS', 'AVANZADA', 'SI', '47'),
    ('DZNARANJO', 'AVANZADA', 'SI', '48'),
    ('DZNARANJOCEOS', 'AVANZADA', 'SI', '49'),
    ('EMERGIAJUR', 'AVANZADA', 'SI', '50'),
    ('EZBORRERO', 'AVANZADA', 'SI', '51'),
    ('EZCRUZ', 'AVANZADA', 'SI', '52'),
    ('EZCRUZCEOS', 'AVANZADA', 'SI', '53'),
    ('EZGAMBA', 'AVANZADA', 'SI', '54'),
    ('EZMURGAS', 'AVANZADA', 'SI', '55'),
    ('EZMURGASCEOS', 'AVANZADA', 'SI', '56'),
    ('EZRAMIREZ', 'AVANZADA', 'SI', '57'),
    ('FINESA', 'AVANZADA', 'SI', '58'),
    ('FINESACEOS', 'AVANZADA', 'SI', '59'),
    ('FZALCALA', 'AVANZADA', 'SI', '60'),
    ('FZARENAS', 'AVANZADA', 'SI', '61'),
    ('FZHENAO', 'AVANZADA', 'SI', '62'),
    ('GRUNALCO', 'AVANZADA', 'SI', '63'),
    ('GRUNALCOCEOS', 'AVANZADA', 'SI', '64'),
    ('GZCAMACHO', 'AVANZADA', 'SI', '65'),
    ('GZCANAS', 'AVANZADA', 'SI', '66'),
    ('GZCANASCEOS', 'AVANZADA', 'SI', '67'),
    ('GZFARELO', 'AVANZADA', 'SI', '68'),
    ('GZFUENTES', 'AVANZADA', 'SI', '69'),
    ('GZJARAMILLO', 'AVANZADA', 'SI', '70'),
    ('GZMEJIA1', 'AVANZADA', 'SI', '71'),
    ('GZNINO', 'AVANZADA', 'SI', '72'),
    ('GZNINOCEOS', 'AVANZADA', 'SI', '73'),
    ('GZPEREZ', 'AVANZADA', 'SI', '74'),
    ('GZPIMIENTA', 'AVANZADA', 'SI', '75'),
    ('GZPIMIENTACEOS', 'AVANZADA', 'SI', '76'),
    ('GZRUBIO', 'AVANZADA', 'SI', '77'),
    ('GZRUBIOCEOS', 'AVANZADA', 'SI', '78'),
    ('HZFARELO', 'AVANZADA', 'SI', '79'),
    ('HZFRANCO', 'AVANZADA', 'SI', '80'),
    ('HZFRANCOCEOS', 'AVANZADA', 'SI', '81'),
    ('HZMONROY', 'AVANZADA', 'SI', '82'),
    ('HZMONROYCEOS', 'AVANZADA', 'SI', '83'),
    ('HZSOLANO', 'AVANZADA', 'SI', '84'),
    ('INSOLVPERSONANATURAL', 'AVANZADA', 'SI', '85'),
    ('INVERST', 'AVANZADA', 'SI', '86'),
    ('IZCORREACEOS', 'AVANZADA', 'SI', '87'),
    ('IZGARCIA', 'AVANZADA', 'SI', '88'),
    ('IZGARCIACEOS', 'AVANZADA', 'SI', '89'),
    ('JPATINOCORFCEOS', 'AVANZADA', 'SI', '90'),
    ('JSAYOCORFCEOS', 'AVANZADA', 'SI', '91'),
    ('JUANZAPATA', 'AVANZADA', 'SI', '92'),
    ('JURIDICOAVANZADA', 'AVANZADA', 'SI', '93'),
    ('JZAVILA', 'AVANZADA', 'SI', '94'),
    ('JZAVILACEOS', 'AVANZADA', 'SI', '95'),
    ('JZBAUTE', 'AVANZADA', 'SI', '96'),
    ('JZBAUTECEOS', 'AVANZADA', 'SI', '97'),
    ('JZBEDOYA', 'AVANZADA', 'SI', '98'),
    ('JZBEDOYACEOS', 'AVANZADA', 'SI', '99'),
    ('JZCARRILLO', 'AVANZADA', 'SI', '100'),
    ('JZCARRILLOCEOS', 'AVANZADA', 'SI', '101'),
    ('JZCOCK', 'AVANZADA', 'SI', '102'),
    ('JZCOCKCEOS', 'AVANZADA', 'SI', '103'),
    ('JZNARANJO', 'AVANZADA', 'SI', '104'),
    ('JZNARANJOCEOS', 'AVANZADA', 'SI', '105'),
    ('JZORLANDO', 'AVANZADA', 'SI', '106'),
    ('JZORLANDOCEOS', 'AVANZADA', 'SI', '107'),
    ('JZPORTILLO', 'AVANZADA', 'SI', '108'),
    ('JZPORTILLOCEOS', 'AVANZADA', 'SI', '109'),
    ('JZPUERTO', 'AVANZADA', 'SI', '110'),
    ('JZPUERTOCEOS', 'AVANZADA', 'SI', '111'),
    ('JZSINISTERRA', 'AVANZADA', 'SI', '112'),
    ('JZSINISTERRACEOS', 'AVANZADA', 'SI', '113'),
    ('JZSUAREZESC', 'AVANZADA', 'SI', '114'),
    ('JZSUAREZESCCEOS', 'AVANZADA', 'SI', '115'),
    ('JZZAPATA', 'AVANZADA', 'SI', '116'),
    ('JZZAPATACEOS', 'AVANZADA', 'SI', '117'),
    ('LITIGIOECORFCEOS', 'AVANZADA', 'SI', '118'),
    ('LZBELTRAN', 'AVANZADA', 'SI', '119'),
    ('LZHENAO', 'AVANZADA', 'SI', '120'),
    ('LZHENAOCEOS', 'AVANZADA', 'SI', '121'),
    ('LZLORA', 'AVANZADA', 'SI', '122'),
    ('LZMASSON', 'AVANZADA', 'SI', '123'),
    ('LZQUICENO', 'AVANZADA', 'SI', '124'),
    ('LZRONDON', 'AVANZADA', 'SI', '125'),
    ('LZRONDONCEOS', 'AVANZADA', 'SI', '126'),
    ('LZVASQUEZ1', 'AVANZADA', 'SI', '127'),
    ('LZVASQUEZ1CEOS', 'AVANZADA', 'SI', '128'),
    ('MDZABOGADOS', 'AVANZADA', 'SI', '129'),
    ('MEGALINEAZJUR', 'AVANZADA', 'SI', '130'),
    ('MEGALINEAZJURANTIOQUIA', 'AVANZADA', 'SI', '131'),
    ('MEGALINEAZJURBOGOTA', 'AVANZADA', 'SI', '132'),
    ('MEGALINEAZJURCENTRAL', 'AVANZADA', 'SI', '133'),
    ('MEGALINEAZJURCEOS', 'AVANZADA', 'SI', '134'),
    ('MEGALINEAZJURCOSTA', 'AVANZADA', 'SI', '135'),
    ('MEGALINEAZJUROCCIDENTE', 'AVANZADA', 'SI', '136'),
    ('MEGALINEAZJURORIENTE', 'AVANZADA', 'SI', '137'),
    ('MNINOCORFCEOS', 'AVANZADA', 'SI', '138'),
    ('MZACOSTA', 'AVANZADA', 'SI', '139'),
    ('MZACOSTACEOS', 'AVANZADA', 'SI', '140'),
    ('MZALZAMORA', 'AVANZADA', 'SI', '141'),
    ('MZALZAMORACEOS', 'AVANZADA', 'SI', '142'),
    ('MZARANGO', 'AVANZADA', 'SI', '143'),
    ('MZARANGOCEOS', 'AVANZADA', 'SI', '144'),
    ('MZBOSSA', 'AVANZADA', 'SI', '145'),
    ('MZBOSSACEOS', 'AVANZADA', 'SI', '146'),
    ('MZCAMARGO', 'AVANZADA', 'SI', '147'),
    ('MZCAMARGOCEOS', 'AVANZADA', 'SI', '148'),
    ('MZESCOBAR', 'AVANZADA', 'SI', '149'),
    ('MZHERNANDEZD', 'AVANZADA', 'SI', '150'),
    ('MZHERNANDEZDCEOS', 'AVANZADA', 'SI', '151'),
    ('MZMEJIA1', 'AVANZADA', 'SI', '152'),
    ('MZMEJIA1CEOS', 'AVANZADA', 'SI', '153'),
    ('MZMELO', 'AVANZADA', 'SI', '154'),
    ('MZMELOCEOS', 'AVANZADA', 'SI', '155'),
    ('MZQUINTERO', 'AVANZADA', 'SI', '156'),
    ('MZQUINTEROCEOS', 'AVANZADA', 'SI', '157'),
    ('MZSOTO', 'AVANZADA', 'SI', '158'),
    ('NDUARTECORF', 'AVANZADA', 'SI', '159'),
    ('NDUARTECORFCEOS', 'AVANZADA', 'SI', '160'),
    ('NZMUNOZ', 'AVANZADA', 'SI', '161'),
    ('NZOSPINA', 'AVANZADA', 'SI', '162'),
    ('NZOSPINACEOS', 'AVANZADA', 'SI', '163'),
    ('OZMEDINA', 'AVANZADA', 'SI', '164'),
    ('OZMEDINACEOS', 'AVANZADA', 'SI', '165'),
    ('PROSSEMZJUR', 'AVANZADA', 'SI', '166'),
    ('PVELASQUEZCORF', 'AVANZADA', 'SI', '167'),
    ('PVELASQUEZCORFCEOS', 'AVANZADA', 'SI', '168'),
    ('PZBUSTOS', 'AVANZADA', 'SI', '169'),
    ('PZBUSTOSCEOS', 'AVANZADA', 'SI', '170'),
    ('PZCADENA', 'AVANZADA', 'SI', '171'),
    ('PZCADENACEOS', 'AVANZADA', 'SI', '172'),
    ('PZJANE', 'AVANZADA', 'SI', '173'),
    ('PZMCBROWN', 'AVANZADA', 'SI', '174'),
    ('PZPIEDRAHITA', 'AVANZADA', 'SI', '175'),
    ('PZPIEDRAHITACEOS', 'AVANZADA', 'SI', '176'),
    ('PZPORRAS', 'AVANZADA', 'SI', '177'),
    ('PZVELASCO', 'AVANZADA', 'SI', '178'),
    ('PZVELASCOCEOS', 'AVANZADA', 'SI', '179'),
    ('RAULBELTRAN', 'AVANZADA', 'SI', '180'),
    ('RECLAMACIONFGA', 'AVANZADA', 'SI', '181'),
    ('RZBELTRAN', 'AVANZADA', 'SI', '182'),
    ('RZBELTRANCEOS', 'AVANZADA', 'SI', '183'),
    ('RZBONILLA', 'AVANZADA', 'SI', '184'),
    ('RZBONILLACEOS', 'AVANZADA', 'SI', '185'),
    ('RZGOMEZ', 'AVANZADA', 'SI', '186'),
    ('RZGOMEZCEOS', 'AVANZADA', 'SI', '187'),
    ('RZHERNANDEZ', 'AVANZADA', 'SI', '188'),
    ('RZHERNANDEZCEOS', 'AVANZADA', 'SI', '189'),
    ('SGAVIRIACORF', 'AVANZADA', 'SI', '190'),
    ('SGAVIRIACORFCEOS', 'AVANZADA', 'SI', '191'),
    ('SZDUMAR', 'AVANZADA', 'SI', '192'),
    ('SZDUMARCEOS', 'AVANZADA', 'SI', '193'),
    ('SZGUZMAN', 'AVANZADA', 'SI', '194'),
    ('SZLEUDO', 'AVANZADA', 'SI', '195'),
    ('SZOLIVEROS', 'AVANZADA', 'SI', '196'),
    ('SZOLIVEROSCEOS', 'AVANZADA', 'SI', '197'),
    ('SZOROZCO', 'AVANZADA', 'SI', '198'),
    ('SZOROZCOCEOS', 'AVANZADA', 'SI', '199'),
    ('SZPOLANIA', 'AVANZADA', 'SI', '200'),
    ('SZPOLANIACEOS', 'AVANZADA', 'SI', '201'),
    ('TZLOSADA', 'AVANZADA', 'SI', '202'),
    ('VZGOMEZ', 'AVANZADA', 'SI', '203'),
    ('YZBERMUDEZ', 'AVANZADA', 'SI', '204'),
    ('YZBERMUDEZCEOS', 'AVANZADA', 'SI', '205'),
    ('AECSAZEXTRA', 'MEDIA', 'SI', '206'),
    ('ASERCORZSASEXTRA', 'MEDIA', 'SI', '207'),
    ('ATMEXTRA', 'MEDIA', 'SI', '208'),
    ('ATMPOST', 'MEDIA', 'SI', '209'),
    ('ATMZMED', 'MEDIA', 'SI', '210'),
    ('COLCARTERAINCEXTRA', 'MEDIA', 'SI', '211'),
    ('COMDINAMICA1POST', 'MEDIA', 'SI', '212'),
    ('COMDINAMICA2POST', 'MEDIA', 'SI', '213'),
    ('COMDINAMICAEXTRA', 'MEDIA', 'SI', '214'),
    ('EMERGIAEXTRA', 'MEDIA', 'SI', '215'),
    ('ERPOEXTRA', 'MEDIA', 'SI', '216'),
    ('EXTRAJURIDICOAVANZADA', 'MEDIA', 'SI', '217'),
    ('EXTRAJURIDICOVENCIDA', 'MEDIA', 'SI', '218'),
    ('MDZEXTRA', 'MEDIA', 'SI', '219'),
    ('MEGALINEAEXTRA', 'MEDIA', 'SI', '220'),
    ('PROSSEMEXTRA', 'MEDIA', 'SI', '221'),
    ('PROSSEMPOST', 'MEDIA', 'SI', '222'),
    ('PROSSEMZMED', 'MEDIA', 'SI', '223'),
    ('RECLAMACIONFGA', 'MEDIA', 'SI', '224'),
    ('REINCAREXTRA', 'MEDIA', 'SI', '225'),
    ('REINCARPOST', 'MEDIA', 'SI', '226'),
    ('SICALEGALEXTRA', 'MEDIA', 'SI', '227'),
    ('VENTASYSERVICIOS1POST', 'MEDIA', 'SI', '228'),
    ('VENTASYSERVICIOS2POST', 'MEDIA', 'SI', '229'),
    ('VENTASYSERVICIOSEXTRA', 'MEDIA', 'SI', '230'),
    ('CEOSZFNGFAG', 'NOGESTION', 'SI', '231'),
    ('CEOSZOAE', 'NOGESTION', 'SI', '232'),
    ('CEOSZOAEZSINFNGFAG', 'NOGESTION', 'SI', '233'),
    ('CLIENTEZSINZNOMBRE', 'NOGESTION', 'SI', '234'),
    ('CODEUDORES', 'NOGESTION', 'SI', '235'),
    ('COMDINAMICAEXTRA', 'NOGESTION', 'SI', '236'),
    ('CONCURSAL', 'NOGESTION', 'SI', '237'),
    ('CONCURSALZRESPETO', 'NOGESTION', 'SI', '238'),
    ('CONCURSALZSALIDA', 'NOGESTION', 'SI', '239'),
    ('DEPURACIONZCASTIGOS', 'NOGESTION', 'SI', '240'),
    ('MDZPYME', 'NOGESTION', 'SI', '241'),
    ('NOGESTION', 'NOGESTION', 'SI', '242'),
    ('NOGESTIONREC', 'NOGESTION', 'SI', '243'),
    ('NOGESTIONZRESPETO', 'NOGESTION', 'SI', '244'),
    ('PATRIMONIOZAUTONOMO', 'NOGESTION', 'SI', '245'),
    (
        'PERSONAJURIDICAZMASIVA',
        'NOGESTION',
        'SI',
        '245'
    ),
    (
        'PERSONAJURIDICAZNOMASIVA',
        'NOGESTION',
        'SI',
        '246'
    ),
    ('PROCZPENALES', 'NOGESTION', 'SI', '247'),
    ('PROSSEMZMEDIANA', 'NOGESTION', 'SI', '248'),
    ('PYME', 'NOGESTION', 'SI', '249'),
    ('RECLAMACIONFGA', 'NOGESTION', 'SI', '250'),
    ('VENTACARTERACISA2020', 'NOGESTION', 'SI', '251'),
    (
        'VENTACARTERACOBRANDOSASDIC2025',
        'NOGESTION',
        'SI',
        '252'
    ),
    (
        'VENTACARTERACOBRANDOSASFEB26',
        'NOGESTION',
        'SI',
        '253'
    ),
    ('VENTACARTERACOBRANZAS', 'NOGESTION', 'SI', '254'),
    (
        'VENTACARTERACOOPERACTIVADIC202',
        'NOGESTION',
        'SI',
        '255'
    ),
    (
        'VENTACARTERAECREDITDIC2025',
        'NOGESTION',
        'SI',
        '256'
    ),
    ('VENTACARTERAJUNIO2026', 'NOGESTION', 'SI', '257'),
    (
        'VENTACARTERAJUNIOFLEXFINTECH25',
        'NOGESTION',
        'SI',
        '258'
    ),
    (
        'VENTACARTERAJUNIOJCAP2025',
        'NOGESTION',
        'SI',
        '259'
    ),
    (
        'VENTACARTERAJUNIOLIQUITTY2024',
        'NOGESTION',
        'SI',
        '260'
    ),
    (
        'VENTACARTERAJUNIONOVARTEC2024',
        'NOGESTION',
        'SI',
        '261'
    ),
    (
        'VENTACARTERAJUNIONOVARTEC2025',
        'NOGESTION',
        'SI',
        '262'
    ),
    (
        'VENTACARTERAJUNIOQNT2024',
        'NOGESTION',
        'SI',
        '263'
    ),
    (
        'VENTACARTERALATOSENSUDIC2025',
        'NOGESTION',
        'SI',
        '264'
    ),
    ('VENTACARTERAQNT2019', 'NOGESTION', 'SI', '265'),
    ('VENTACARTERAQNT2020', 'NOGESTION', 'SI', '266'),
    (
        'VENTACARTERAQNTABR2023',
        'NOGESTION',
        'SI',
        '267'
    ),
    (
        'VENTACARTERAQNTDIC2022',
        'NOGESTION',
        'SI',
        '268'
    ),
    (
        'VENTACARTERAQNTJUNIO2022',
        'NOGESTION',
        'SI',
        '269'
    ),
    (
        'VENTACARTERAQNTMAYO2022',
        'NOGESTION',
        'SI',
        '270'
    ),
    (
        'VENTAREFINANCIASUSTITUCION2014',
        'NOGESTION',
        'SI',
        '271'
    ),
    ('VENTAZCREARPAISZ2018', 'NOGESTION', 'SI', '272'),
    (
        'VENTAZSISTEMCOBROZ2018',
        'NOGESTION',
        'SI',
        '273'
    ),
    ('CEOPYMETEMP', 'NOGESTIONTEMPORAL', 'SI', '274'),
    ('NOGESTEMP', 'NOGESTIONTEMPORAL', 'SI', '275'),
    (
        'NOGESTIONTEMPORAL',
        'NOGESTIONTEMPORAL',
        'SI',
        '276'
    ),
    (
        'PERSONAJURIDICA',
        'NOGESTIONTEMPORAL',
        'SI',
        '277'
    ),
    (
        'PERSONAJURIDICAZMASIVA',
        'NOGESTIONTEMPORAL',
        'SI',
        '278'
    ),
    (
        'PERSONAJURIDICAZMASIVA5',
        'NOGESTIONTEMPORAL',
        'SI',
        '279'
    ),
    (
        'PERSONAJURIDICAZNOMASIVA',
        'NOGESTIONTEMPORAL',
        'SI',
        '280'
    ),
    (
        'PERSONAJURIDICAZNOMASIVAZRED',
        'NOGESTIONTEMPORAL',
        'SI',
        '281'
    ),
    ('PREMIUM', 'NOGESTIONTEMPORAL', 'SI', '282'),
    ('AECSAZMED', 'TEMPRANA', 'SI', '283'),
    ('ASERFINC90', 'TEMPRANA', 'SI', '284'),
    ('ASERFINCZMED', 'TEMPRANA', 'SI', '285'),
    ('CALLCENTER', 'TEMPRANA', 'SI', '286'),
    ('COBRANDOZMED', 'TEMPRANA', 'SI', '287'),
    ('HIP30', 'TEMPRANA', 'SI', '288'),
    ('HIP60', 'TEMPRANA', 'SI', '289'),
    ('LIBRANZAS', 'TEMPRANA', 'SI', '290'),
    ('MONO30', 'TEMPRANA', 'SI', '291'),
    ('MONO60', 'TEMPRANA', 'SI', '292'),
    ('MULTI30', 'TEMPRANA', 'SI', '293'),
    ('MULTI60', 'TEMPRANA', 'SI', '294'),
    ('OTROS30', 'TEMPRANA', 'SI', '296'),
    ('RECLAMACIONFGA', 'TEMPRANA', 'SI', '297'),
    ('TEMPRANA', 'TEMPRANA', 'SI', '298'),
    ('TRANQUIFINANZAS90', 'TEMPRANA', 'SI', '299');